#!/bin/bash

# Colors
red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
blue='\033[0;34m'
purple='\033[0;35m'
cyan='\033[0;36m'
white='\033[0;37m'
f='\033[0m' # Reset color

# Function to download files from GitHub
download_from_github() {
    file="$1"
    url="https://raw.githubusercontent.com/RDY8799/VPS-tools/main/$file"
    destination="/usr/local/bin/$file"
    echo -e "${yellow}Downloading ${cyan}$file${yellow}..."

    # Check if the file already exists
    if [ -e "$destination" ]; then
        echo -n -e "File ${red}$file${white} already exists. Do you want to overwrite it? (${red}y${white}/${green}n${white}): "
        read -r choice
        if [ "$choice" = "y" ]; then
            rm -f "$destination"
        else
            echo -e "${yellow}Skipping ${cyan}$file${yellow}"
            return
        fi
    fi

    # Download the file
    curl -sL "$url" -o "$destination"
    chmod +x "$destination"
    echo -e "${green}$file${yellow} downloaded and saved to ${cyan}$destination${f}"
}

# Download files from GitHub and save them in /usr/local/bin
download_from_github "RDYDROPBEAR"
download_from_github "RDYSQUIDPROXY"
download_from_github "RDYSSLH"
download_from_github "RDYSTUNNEL"
download_from_github "STRINGS"
download_from_github "menu"
download_from_github "TROJAN"
download_from_github "RDYBADVPN"
download_from_github "PORTCHANGER"

# Execute the 'menu' command if it exists
if [ -x "/usr/local/bin/menu" ]; then
    echo -e "${blue}Executing 'menu'...${f}"
    /usr/local/bin/menu
else
    echo -e "${red}The 'menu' file does not exist or is not executable.${f}"
fi
