#!/bin/bash

RDYBADVPN() {
    clear
    echo -e "$DIVIS"
    echo -e "${blue}--${yellow}>>${f}${white} menu${blue}/${yellow}MENU DE INSTALAÇÃO${blue}/${mag}BADVPN${f} ${yellow}[${blue}v${yellow}]${yellow}=${f}${white} Voltar${f}"
    echo -e "$DIVIS"
    echo -e "${green}#####${white} IP:${cyano}  $ip ${f}"
    echo -e "${green}#####${white} $SYSTEM:${cyano}  $system_info ${f}"
    echo -e "${green}#####${white} $USER:${cyano}  $USERPROFILENAME ${f}"
    echo -e "$DIVIS"

    echo -e "${white}//${yellow}//${green}//${mag}//    ${yellow}INSTALADOR BADVPN${f}"
    echo -e "$DIVIS"

    if [[ "$BADVPNSTATUS" == 'YES' ]]; then
        service="udpgw"
        if pgrep -x "$service" > /dev/null; then
            echo -ne "${yellow}[${blue}p${yellow}]${yellow}=${f}${white} $STOPSERVICE ${f}${BADVPNINFO}"
        else
            echo -ne "${yellow}[${blue}s${yellow}]${yellow}=${f}${white} $STARTSERVICE ${f}${BADVPNINFO}"
        fi

        echo -e "$DIVIS"
        echo -e "${yellow}[${blue}01${yellow}]${yellow}=${f}${white} DESINSTALAR BADVPN ${f}"
        echo -e "${yellow}[${blue}00${yellow}]${yellow}=${f}${white} $EXIT ${f}"
        echo -e "$DIVIS"

        echo -ne "${yellow}Opção:${f} "
        read -r option

        case $option in
            v)
                $mainmenu
                ;;
            p | P)
                pkill badvpn
                RDYSPINNER
                echo -e "${white}//${yellow}//${green}//${mag}//    ${red}(STOP) ${blue}OPERAÇÃO ${green}CONCLUÍDA!${f}"
                echo -ne "${white}//${yellow}//${green}//${mag}//    ${green}Pressione uma tecla para retornar...${f}"
                read -n1 -r
                RDYBADVPN
                ;;
            s | S)
                badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 1000 --max-connections-for-client 10 &
                RDYSPINNER
                echo -e "${white}//${yellow}//${green}//${mag}//    ${red}(START) ${blue}OPERAÇÃO ${green}CONCLUÍDA!${f}"
                echo -ne "${white}//${yellow}//${green}//${mag}//    ${green}Pressione uma tecla para retornar...${f}"
                read -n1 -r
                RDYBADVPN
                ;;
            1 | 01)
                echo -e "${white}//${yellow}//${green}//${mag}//    ${green}DESINSTALAR BADVPN?${f}"
                read -p "[s/n]: " -r -e -i n REMOVE
                if [[ "$REMOVE" == 's' ]]; then
                    echo -e "${white}//${yellow}//${green}//${mag}//    ${blue}DESINSTALANDO, ${green}AGUARDE...${f}"
                    pkill badvpn
                    RDYSPINNER
                    if [[ "$OS" == 'debian' ]]; then
                        apt-get remove --purge BADVPN -y
                    else
                        yum remove BADVPN -y
                    fi
                    RDYSPINNER
                    echo -e "${white}//${yellow}//${green}//${mag}//    ${blue}DESINSTALAÇÃO ${green}CONCLUÍDA!${f}"
                    echo -ne "${white}//${yellow}//${green}//${mag}//    ${green}Pressione uma tecla para retornar ao menu inicial...${f}"
                    read -n1 -r
                    $mainmenu
                else
                    echo -e "${white}//${yellow}//${green}//${mag}//    ${blue}OPERAÇÃO CANCELADA!${f}\n"
                    echo -ne "${white}//${yellow}//${green}//${mag}//    ${green}Pressione uma tecla para retornar ao menu inicial...${f}"
                    read -n1 -r
                    $mainmenu
                fi
                ;;
            00)
                exit
                ;;
            *)
                echo -e "${red}Opção inválida!${f}\n"
                sleep 2
                $mainmenu
                ;;
        esac
    elif [[ "$BADVPNSTATUS" == 'NO' ]]; then
        echo -e "$BADVPNINFO"
        echo -e "$DIVIS"
        echo -ne "${white}//${yellow}//${green}//${mag}//    ${yellow}CONTINUAR COM A CONFIGURAÇÃO DO BADVPN?${f}"
        read -p " [s/n]: " -r -e -i s yesNo
        echo -e "$DIVIS"

        if [[ "$yesNo" == 's' ]]; then
            echo -ne "${white}(${mag}<${green}i${mag}>${white})    ${blue}A porta 7300 já vem definida por padrão na configuração BADVPN.${f}"
            echo -e "$DIVIS"
            echo -e "${white}//${yellow}//${green}//${mag}//    ${mag}Pressione uma tecla para iniciar...${f}"
            read -n1 -r
            echo -e "${white}//${yellow}//${green}//${mag}//    ${blue}INICIANDO INSTALAÇÃO ${green}AGUARDE...${f}"
            if [[ "$OS" == 'debian' ]]; then
                apt-get update -y
                apt-get install -y gcc make g++ openssl build-essential cmake
            else
                yum update -y
                yum install -y gcc make g++ openssl build-essential cmake
            fi

            wget https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/badvpn/badvpn-1.999.128.tar.bz2 -O badvpn-1.999.128.tar.bz2
            tar -xf badvpn-1.999.128.tar.bz2
            mkdir -p /etc/badvpn-install
            cd /etc/badvpn-install || exit
            cmake ~/badvpn-1.999.128 -DBUILD_NOTHING_BY_DEFAULT=1 -DBUILD_UDPGW=1
            make install
            rm -rf /etc/badvpn-install
            cd ~ || exit
            rm -rf badvpn.sh badvpn-1.999.128/ badvpn-1.999.128.tar.bz2
            echo -e "${green}Executando em screem (Aguarde 5 segundos...)${f}"
            sleep 5
            screen -dm badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 1000 --max-connections-for-client 10
            echo -e "${white}//${yellow}//${green}//${mag}//    ${blue}CONFIGURAÇÃO CONCLUÍDA COM ${green}SUCESSO!${f}"
            echo -e "${white}//${yellow}//${green}//${mag}//    ${green}√ ${white}PORTA BADVPN:${red} 7300 ${f}"
            echo -e "$DIVIS"
            echo -ne "${white}//${yellow}//${green}//${mag}//    ${green}Pressione uma tecla para retornar ao menu inicial...${f}"
            read -n1 -r
            $mainmenu
        elif [[ "$yesNo" == 'n' ]]; then
            echo -e "$DIVIS"
            echo -e "${white}//${yellow}//${green}//${mag}//    ${blue}OPERAÇÃO CANCELADA!${green} Pressione uma tecla para retornar ao menu inicial...${f}"
            read -n1 -r
            echo -e "$DIVIS"
            $mainmenu
        elif [[ "$yesNo" == 'v' ]]; then
            $mainmenu
        else
            echo -e "${white}//${yellow}//${green}//${mag}//    ${blue}OPÇÃO INVÁLIDA!${f}"
            echo -ne "${white}//${yellow}//${green}//${mag}//    ${green}Pressione uma tecla para retornar ao menu inicial...${f}"
            read -n1 -r
            $mainmenu
        fi
    else
        echo -e "${white}//${yellow}//${green}//${mag}//    ${red}OPS! HÁ ALGO DE ERRADO!\n${mag}Favor entrar em contato com seu fornecedor! ${mag}(BADVPN)${f}"
        echo -ne "${white}//${yellow}//${green}//${mag}//    ${green}Pressione uma tecla para retornar ao menu inicial...${f}"
        read -n1 -r
        $mainmenu
    fi
}

RDYBADVPN
