#!/bin/bash

# CORES
white="\033[1;37m";
red="\033[1;31m";
green="\033[1;32m";
yellow="\033[1;33m";
cyano="\033[1;36m";
blue="\033[1;34m";
mag="\033[1;35m";

# de fundo
magneta="\033[1;37;45m";
f="\033[0m";

VERSION="v1.0.1";
ABOUT="SOBRE";
USERNAME="USUÁRIO";
SYSTEM="SISTEMA";
USERPROFILENAME=$USER;

DIVIS="\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m";


NEWUSER="NOVO USUÁRIO";
NEWUSERTIME="NOVO USUÁRIO TEMPORÁRIO";
USERMONITOR="MONITOR";
DELETEUSER="APAGAR USUÁRIO";
CHANGELIMIT="ALTEREAR LIMITE DE CONEXÃO SIMULÂNEA";
CHANGEDATE="ALTERAR DATA DE EXPIRAÇÃO";
CHANGEPASSWORD="ALTERAR SENHA";
REMOVELIMITUSER="REMOVER LIMITE DE CON. SIMULT.";
DELETEEXPIREDUSERS="APAGAR USUÁRIOS EXPIRADOS";
USERDETAILS="INFO. SOBRE USUÁRIOS";
DISCONNECTUSER="DESCONECTAR USUÁRIO";
BACKUPUSERS="BACKUP DE TODOS OS LOGINS CRIADOS";
RESTOREBACKUP="RECUPERAR BACKUP EXISTENTE";
EXIT="SAIR";
OP_NOT_DEVELOPED="OPÇÃO NÃO DESENVOLVIDA";

CREATE_BANNER="CRIAR BANNER";
CLEARCACHE="APAGAR CACHE E INODES";
ADD_REMOVE_HOSTS="ADICIONAR/REMOVER HOSTS"

###### CONF. RAM/MEMÓRIA
CPU_USADA="CPU USADA:";
RAM_USADA="RAM USADA:";
MB="MB";
LIVRE="LIVRE:";
SWAP="SWAP";
###### FIM


FIREWALL="FIREWALL";
UPDATE_SYSTEM="ATUALIZAR SISTEMA";
SPEEDTEST="TESTAR VELOCIDADE DE BANDA-${magneta}SPEEDTEST$f";
REBOOT_SYSTEM="REINIICIAR SISTEMA";
NOTIFICATION="Notificações";
MENU_INSTALL="INSTALADOR/COFIGURAR";
MANAGE_USERS="GERENCIAMENTO DE USUÁRIOS";
TOOLS="FERRAMENTAS";
ABOUT="SOBRE";

about="© ${blue}Copyright ${yellow}RDY ${red}SOFTWARE ${yellow}{${red}}$f ${blue}2024$f"
cat -n /etc/issue |grep 1 |cut -d' ' -f6,7,8 |sed 's/1//' |sed 's/	//' > /etc/so
# VERIFICAR O IP DO SERVIDOR
ip=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)

if [[ "$ip" = "" ]]; then
ip=$(wget -qO- ipv4.icanhazip.com)
fi

IP=$ip

# ESTADO DE RAM
CPU=$(ps aux  | awk 'BEGIN { sum = 0 }  { sum += sprintf("%f",$3) }; END { printf " " "%.2f" "%%", sum}')
totalram=$(free | grep Mem | awk '{print $2}')
usedram=$(free | grep Mem | awk '{print $3}')
freeram=$(free | grep Mem | awk '{print $4}')
swapram=$( cat /proc/meminfo | grep SwapTotal | awk '{print $2}')

# TIPO DE SISTEMA
if [[ -e /etc/debian_version ]]; then
	OS=debian
	GROUPNAME=nogroup
	RCLOCAL='/etc/rc.local'
elif [[ -e /etc/centos-release || -e /etc/redhat-release ]]; then
	OS=centos
	GROUPNAME=nobody
	RCLOCAL='/etc/rc.d/rc.local'
else
	echo "Looks like you aren't running this installer on a Debian, Ubuntu or CentOS system"
	exit 2
fi

RDYCTRLC(){
printf "\rOOuuu! Me parou!!"
}

#trap RDYCTRLC SIGINT

#while true; do
#read crap
#printf "RDY SOFTWARE 2019"
#done

# PROGRESS BAR
RDYSPINNER()
{
    local pid=$!
    local delay=0.50
    local spinstr='|/-\'
	tput civis -- invisible
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf " ${yellow}[${mag}%c${red}]$f  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done
    printf "    \b\b\b\b"
	tput cnorm -- normal
}